### ISSUE TITLE
E4- Finalização da pagina cadastro de gastos

### ISSUE THREAD

**Issue by GleystonGSilva** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-1-e1-proj-web-t06-portal-financeiro#74]

**Comment by LucySuxo** [comment]
Lucy: Realizei a implementação do formulário para cadastro dos gastos. O formulário possui quatro campos de entrada: Categoria (seleção), Descrição, Dia (com calendário) e Valor. A funcionalidade também foi implementada com sucesso.
